import type { Metadata } from "next";
import { Inter } from "next/font/google";
import userTheme from "../../themes/Theme";
import adminTheme from "../../themes/adminTheme";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <ThemeSelector>
          <body className={inter.className}>{children}</body>
        </ThemeSelector>
      </AuthProvider>
    </html>
  );
}

const ThemeSelector = ({children}) => {

  const {isAdmin} = useAuth();

return <ThemeProvider theme={isAdmin?adminTheme:userTheme}>
  {children}
</ThemeProvider>
}

